groups:
  - name: example
    rules:

      - alert: ScrapeApiDown
        expr: up == 0
        for: 60s
        labels:
          severity: warning
        annotations:
          summary: "Instance {{ $labels.instance }} down"
          description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 3 minutes."

      - alert: app_conv_install_total
        expr: sum(app_conv_install_total) < 3000
        for: 60s
        labels:
          severity: warning
        annotations:
          summary: "安装少于 3000"
